[package]
name = "for_each_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
nightly = []

[dependencies]
proc-macro-error = { version = "1.0", default-features = false }
